package com.odeyalo.sonata.harmony.service.upload;

import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.buffer.DefaultDataBuffer;
import org.springframework.core.io.buffer.DefaultDataBufferFactory;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;
import testing.spring.web.FilePartStub;

import java.io.IOException;

class AmazonS3FileUploaderDelegateTest {
    AmazonS3FileUploaderDelegate testable = new AmazonS3FileUploaderDelegate();

    @Test
    void uploadFile() throws IOException {
        var uploadTarget = getFileUploadTarget();

        testable.uploadFile(uploadTarget)
                .as(StepVerifier::create)
                .expectNext(FileUrl.urlOnly("https://cdn.sonata.com/autogeneratedid"))
                .verifyComplete();
    }

    private static FileUploadTarget getFileUploadTarget() throws IOException {
        var image = new ClassPathResource("./img/test-image.png");

        DefaultDataBufferFactory bufferFactory = new DefaultDataBufferFactory();

        DefaultDataBuffer dataBuffer = bufferFactory.wrap(image.getContentAsByteArray());

        FilePartStub file = new FilePartStub(Flux.just(dataBuffer));

        return FileUploadTarget.builder()
                .id("uniqueid")
                .filePart(file)
                .build();
    }
}