package com.odeyalo.sonata.harmony.service.upload.amazon;

import com.odeyalo.sonata.harmony.service.upload.FileUploadTarget;
import com.odeyalo.sonata.harmony.service.upload.FileUploaderDelegate;
import com.odeyalo.sonata.harmony.service.upload.FileUrl;
import org.jetbrains.annotations.NotNull;
import reactor.core.publisher.Mono;

public class AmazonS3FileUploaderDelegate implements FileUploaderDelegate {

    @Override
    @NotNull
    public Mono<FileUrl> uploadFile(@NotNull FileUploadTarget file) {

        return Mono.just(FileUrl.urlOnly("https://cdn.sonata.com/autogeneratedid"));
    }
}
