package com.odeyalo.sonata.harmony.service.upload;

import org.jetbrains.annotations.NotNull;
import reactor.core.publisher.Mono;

public class AmazonS3FileUploaderDelegate implements FileUploaderDelegate {

    @Override
    @NotNull
    public Mono<FileUrl> uploadFile(@NotNull FileUploadTarget file) {

        return Mono.just(FileUrl.urlOnly("https://cdn.sonata.com/autogeneratedid"));
    }
}
